q2: AVLTree.o AVLTreeNode.o analysis.o main.o
	g++ AVLTree.o AVLTreeNode.o analysis.o main.o -o q2

AVLTree.o : AVLTree.cpp
	g++ -c AVLTree.cpp

AVLTreeNode.o : AVLTreeNode.cpp
	g++ -c AVLTreeNode.cpp

analysis.o : analysis.cpp
	g++ -c analysis.cpp

main.o : main.cpp
	g++ -c main.cpp
